[tool.poetry]
name = "linux-zuru"
version = "0.1.0"
description = "List directory contents like ls command"
authors = ["Abhishek Raj"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
